# Generated by Django 5.1.6 on 2025-04-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_project_image_url_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
