# Generated by Django 5.1.6 on 2025-04-07 20:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_project_image_project_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
