name: Garder Render Allumer

on:
  schedule:
    - cron: '*/10 * * * *'  
  workflow_dispatch:

jobs:
  ping-render:
    runs-on: ubuntu-latest

    steps:
    - name: Call Render API
      run: |
        curl -s -o /dev/null -w "%{http_code}" https://ton-backend.onrender.com/api/health/
