name: Garder Render Allumer

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping-render:
    runs-on: ubuntu-latest

    steps:
      - name: Call Render API
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://https://portfolio-backend-shln.onrender.com/api/projets
